# Generated by Django 6.0.6 on 2026-06-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa_do_mundo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='jogadores',
        ),
        migrations.AddField(
            model_name='partida',
            name='jogadores_casa',
            field=models.ManyToManyField(blank=True, related_name='jogadores_time_da_casa', to='copa_do_mundo.jogador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='jogadores_fora',
            field=models.ManyToManyField(blank=True, related_name='jogadores_time_de_fora', to='copa_do_mundo.jogador'),
        ),
    ]
